package com.model;
// Generated 2017-5-11 13:11:05 by Hibernate Tools 5.2.1.Final


import java.util.Set;

/**
 * Album generated by hbm2java
 */
public class Album implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 12238863614515395L;
	private Integer id;
	private User user;
	private String photo;
	private Set <Albumc> albumcs = null ;
	public Album() {
	}

	public Album(User user, String photo) {
		this.user = user;
		this.photo = photo;
	}

	public Album(User user, String photo, Set <Albumc> albumcs) {
		this.user = user;
		this.photo = photo;
		this.albumcs = albumcs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public Set <Albumc> getAlbumcs() {
		return this.albumcs;
	}

	public void setAlbumcs(Set <Albumc> albumcs) {
		this.albumcs = albumcs;
	}

}
