package com.model;
// Generated 2017-5-11 13:11:05 by Hibernate Tools 5.2.1.Final


import java.util.Set;

/**
 * Blog generated by hbm2java
 */
public class Blog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5505822337696866666L;
	private Integer id;
	private String title;
	private String content;
	private String type;
	private String scope;
	private int hit;
	private Set<Blogc> blogcs = null;
	private Set<Collection> collections = null;

	public Blog() {
	}

	public Blog( String title, String content, String type, String scope, int hit) {
		this.title = title;
		this.content = content;
		this.type = type;
		this.scope = scope;
		this.hit = hit;
	}

	public Blog( String title, String content, String type, String scope, int hit, Set <Blogc> blogcs,
			Set<Collection> collections) {
		this.title = title;
		this.content = content;
		this.type = type;
		this.scope = scope;
		this.hit = hit;
		this.blogcs = blogcs;
		this.collections = collections;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getScope() {
		return this.scope;
	}

	public void setScope(String scope) {
		this.scope = scope;
	}

	public int getHit() {
		return this.hit;
	}

	public void setHit(int hit) {
		this.hit = hit;
	}

	public Set<Blogc> getBlogcs() {
		return this.blogcs;
	}

	public void setBlogcs(Set<Blogc> blogcs) {
		this.blogcs = blogcs;
	}

	public Set<Collection> getCollections() {
		return this.collections;
	}

	public void setCollections(Set<Collection> collections) {
		this.collections = collections;
	}

}
