package com.model;
// Generated 2017-5-11 13:11:05 by Hibernate Tools 5.2.1.Final

/**
 * Blogc generated by hbm2java
 */
public class Blogc implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = -8995688656087225183L;
	private Integer id;
	private Blog blog;
	private User user;
	private String text;
	private Integer nextId;

	public Blogc() {
	}

	public Blogc(Blog blog, User user, String text) {
		this.blog = blog;
		this.user = user;
		this.text = text;
	}

	public Blogc(Blog blog, User user, String text, Integer nextId) {
		this.blog = blog;
		this.user = user;
		this.text = text;
		this.nextId = nextId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Blog getBlog() {
		return this.blog;
	}

	public void setBlog(Blog blog) {
		this.blog = blog;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Integer getNextId() {
		return this.nextId;
	}

	public void setNextId(Integer nextId) {
		this.nextId = nextId;
	}

}
