package com.model;
// Generated 2017-5-11 13:11:05 by Hibernate Tools 5.2.1.Final

/**
 * Albumc generated by hbm2java
 */
public class Albumc implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 2367684738543330788L;
	private int id;
	private Album album;
	private User user;
	private String text;
	private Integer nextId;

	public Albumc() {
	}

	public Albumc(int id, Album album, User user, String text) {
		this.id = id;
		this.album = album;
		this.user = user;
		this.text = text;
	}

	public Albumc(int id, Album album, User user, String text, Integer nextId) {
		this.id = id;
		this.album = album;
		this.user = user;
		this.text = text;
		this.nextId = nextId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Integer getNextId() {
		return this.nextId;
	}

	public void setNextId(Integer nextId) {
		this.nextId = nextId;
	}

}
