package com.model;
// Generated 2017-5-11 13:11:05 by Hibernate Tools 5.2.1.Final

/**
 * Collection generated by hbm2java
 */
public class Collection implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7734680678340302826L;
	private Integer id;
	private Blog blog;
	private User user;

	public Collection() {
	}

	public Collection(Blog blog, User user) {
		this.blog = blog;
		this.user = user;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Blog getBlog() {
		return this.blog;
	}

	public void setBlog(Blog blog) {
		this.blog = blog;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
