package com.model;
// Generated 2017-5-11 13:11:05 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1990718229779191835L;
	private Integer id;
	private String number;
	private String password;
	private String name;
	private short level;
	private String img;
	private Integer hit;
	private Date regtime;
	private String question;
	private Set<Albumc> albumcs = null;
	private Blog blog;
	private Set<Blogc> blogcs = null;
	private Set <Collection> collections = null;
	private Set <Album> albums = null;
	private UserMessage userMessage;

	public User() {
	}

	public User(String number, String password, short level) {
		this.number = number;
		this.password = password;
		this.level = level;
	}

	public User(String number, String password, String name, short level, String img, Integer hit, Date regtime,
			String question, Set<Albumc> albumcs, Blog blog, Set<Blogc> blogcs, Set<Collection> collections, Set<Album> albums, UserMessage userMessage) {
		this.number = number;
		this.password = password;
		this.name = name;
		this.level = level;
		this.img = img;
		this.hit = hit;
		this.regtime = regtime;
		this.question = question;
		this.albumcs = albumcs;
		this.blog = blog;
		this.blogcs = blogcs;
		this.collections = collections;
		this.albums = albums;
		this.userMessage = userMessage;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public short getLevel() {
		return this.level;
	}

	public void setLevel(short level) {
		this.level = level;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public Integer getHit() {
		return this.hit;
	}

	public void setHit(Integer hit) {
		this.hit = hit;
	}

	public Date getRegtime() {
		return this.regtime;
	}

	public void setRegtime(Date regtime) {
		this.regtime = regtime;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public Set<Albumc> getAlbumcs() {
		return this.albumcs;
	}

	public void setAlbumcs(Set <Albumc> albumcs) {
		this.albumcs = albumcs;
	}

	public Blog getBlog() {
		return this.blog;
	}

	public void setBlog(Blog blog) {
		this.blog = blog;
	}

	public Set<Blogc> getBlogcs() {
		return this.blogcs;
	}

	public void setBlogcs(Set<Blogc> blogcs) {
		this.blogcs = blogcs;
	}

	public Set<Collection> getCollections() {
		return this.collections;
	}

	public void setCollections(Set<Collection> collections) {
		this.collections = collections;
	}

	public Set<Album> getAlbums() {
		return this.albums;
	}

	public void setAlbums(Set<Album> albums) {
		this.albums = albums;
	}

	public UserMessage getUserMessage() {
		return this.userMessage;
	}

	public void setUserMessage(UserMessage userMessage) {
		this.userMessage = userMessage;
	}

}
