package com.model;
// Generated 2017-5-11 13:11:05 by Hibernate Tools 5.2.1.Final

/**
 * UserMessage generated by hbm2java
 */
public class UserMessage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2517721514378456272L;
	private int id;
	private User user;
	private String name;
	private String sex;
	private String img;
	private Integer officephone;
	private String design;
	private String email;

	public UserMessage() {
	}

	public UserMessage(User user, String name, String sex) {
		this.user = user;
		this.name = name;
		this.sex = sex;
	}

	public UserMessage(User user, String name, String sex, String img, Integer officephone, String design,
			String email) {
		this.user = user;
		this.name = name;
		this.sex = sex;
		this.img = img;
		this.officephone = officephone;
		this.design = design;
		this.email = email;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public Integer getOfficephone() {
		return this.officephone;
	}

	public void setOfficephone(Integer officephone) {
		this.officephone = officephone;
	}

	public String getDesign() {
		return this.design;
	}

	public void setDesign(String design) {
		this.design = design;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
